### ISSUE TITLE
repush to directory with multiple files doesnt copy files correctly

### ISSUE THREAD

**Issue by lschwetlick** [reHackable/scripts#11]
repush works fine when I provide a single file. 

However, when I give it a list of files 

`bash repush.sh -o /Papers test.pdf test2.pdf test3.pdf`

something goes wrong. It creates one pdf on the remarkable in the correct folder with the contents of the first file and the name of the last file. The middle files sometimes appear as _tmp_repush_test2_tmp_repush_.pdf files in the top directory. 

I'm on MacOs and also had this grep problem (https://github.com/reHackable/scripts/issues/8)

**Comment by CTXz** [comment]
Interesting, thanks for the feedback. I'll take a look at it as soon as I find the time to do so.

**Comment by CTXz** [comment]
Sorry for taking so long, I have been busy with numerous other projects recently.

As of commit 67b15a3dc448a954813f420fa050c9be56ac8550, this issue should no longer occur.
