### ISSUE TITLE
Failed to establish connection with the device!

### ISSUE THREAD

**Issue by git1219** [reHackable/scripts#18]
I am running a virtual (Parallels) Ubuntu linux installation on a MacBook and
bash ./repush.sh Zh.pdf
produces the following error message:
"Failed to establish connection with the device!"

ping 10.11.99.1 (USB connection)
works fine and also I can also ssh into the rM, that is, 
ssh root@10.11.99.1
works.

Any ideas how to resolve this issue?

**Comment by CTXz** [comment]
Is the web interface enabled?

**Comment by git1219** [comment]
Yes, I enabled the web interface with:
rM, Storage, Enable USB web interface.

**Comment by CTXz** [comment]
On [line 520 of repush](https://github.com/reHackable/scripts/blob/master/host/repush.sh#L520), would you mind removing the `-q` option.

Then run repush via USB and provide the output here.

**Comment by git1219** [comment]
OK, I removed the -q option on line 520 of repush. The resulting output is:

```
bash ./repush.sh Zh.pdf
unix_listener: cannot bind to path remarkable-ssh.0bzvKN3CYNNVzpMn: Operation not permitted
repush: Failed to establish connection with the device!
```

**Comment by CTXz** [comment]
Odd, you do not have the permissions to access the control socket, which allows the script to use a single SSH session throughout its entire runtime.

If there's a file starting with `remarkable-ssh` within the directory you're executing `repush.sh` from, delete it and try to run repush again. If that fails, perhaps executing the script with sudo rights will fix it?

Alternatively you could remove all instances of `-S remarkable-ssh` in the script. The only issue here is that the script will demand your SSH password for every interaction between the device and the host. You could work this around by setting up a [ssh key](https://remarkablewiki.com/tech/ssh).

**Comment by git1219** [comment]
I did not find a file starting with `remarkable-ssh` within the directory you're executing `repush.sh` from. 

However, I created a new script repush-modified.sh, where I removed all instances of `-S remarkable-ssh` as you suggested. I also created an ssh keypair so that I don't have to enter the root password of the rM every time. This works; the output is:

```
repush-modified.sh Zh.pdf 
sh: xauth: command not found
sh: xauth: command not found
sh: xauth: command not found
sh: xauth: command not found
sh: xauth: command not found
Zh.pdf                                 100%   55KB 874.6KB/s   00:00    
sh: xauth: command not found
No ControlPath specified for "-O" command
repush: Successfully transferred 1 out of 1 files
```
As you see, several warnings are created but the file is successfully transferred to the rM :-)

**Comment by CTXz** [comment]
Great, to eliminate the xauth issues, simply install xauth:

```
$ sudo apt install xauth
```

I'll render this issue as solved. Since this seems to be an issue on your side, rather than the scripts side, there isn't anything that needs to be fixed here.
