### ISSUE TITLE
repush fails

### ISSUE THREAD

**Issue by florian-wagner** [reHackable/scripts#2]
Two things:

1. Pushing files to the remarkable did not work so far `Failed to push file! Retry? [Y/n]: Y` What could be the reason? I also tried the pdf2remarkable script. While this copies the files to the device, they don't appear under "My files".
2. Saying "no" initializes a retry anyway:
```
Failed to push file! Retry? [Y/n]: n
Pushing 'paper.pdf'...
```

**Comment by Ameb** [comment]
Have you enabled the USB web interface? Under **rM Settings > Storage**. `repush.sh` uses it.
Just fixed point 2.

**Comment by florian-wagner** [comment]
Ah, okay sorry. I will try again. Thought it uses ssh as the pdf2remarkable script.

**Comment by Ameb** [comment]
Maybe the [wiki](https://github.com/reHackable/scripts/wiki/repush.sh) can help. If the problem was the USB web interface, then it also caused #1.

**Comment by florian-wagner** [comment]
Sorry again. I din't even saw that. Great work!
