### ISSUE TITLE
repush: Can't send file over wifi

### ISSUE THREAD

**Issue by geirawsm** [reHackable/scripts#29]
Hi 👋

I have problem with transferring files to my Remarkable 2 through ssh on my wireless network.

When running `repush -r x.x.x.x pdffile.pdf`, it hangs for about a minute or so then gives the following message:
```
repush: pdffile.pdf: Failed
repush: Is the WebUI enabled in the settings? (See: https://github.com/reHackable/scripts/wiki/repush.sh)
Failed to push file! Retry? [Y/n]:
```

I have enabled WebUI when I tested transferring with USB (which works fine), but the option is not available to toggle in the menu when USB is not connected.

- Remarkable software version: 2.4.1.30
- repush-script updated today from raw file

**Comment by avephill** [comment]
Also having this problem

**Comment by notDavid** [comment]
Fyi, probably a duplicate...: https://github.com/reHackable/scripts/issues/20#issuecomment-573456176

**Comment by geirawsm** [comment]
Cheers @notDavid, I'll await a new version.
