### ISSUE TITLE
Sleep time too short to generate meta data file

### ISSUE THREAD

**Issue by schaefischaefi** [reHackable/scripts#4]
Hi,
first of all: thanks to Patrik ans the other contributors for this collection of scrips. I am working only on Linux and without this the remarkable would be useless to me.

*Sleep time too short to generate meta data file*
Description:
Transferring a bundle of pdf-files with repush.sh , for some files the error message appears:
"Failed to access remote metdata for 'myfile.pdf'"

Reproducible: yes, always

Analysis:
I extended the sleep time in line 248 from 0.1, to 1.0 and then to 2.0 and the error disappears. Obviously the sleep time is too short. Interesting is that the time to generate the metadata does not depend on the file size. Larger files are pushed without problems and small files may have problems. 

Workaround:
Extend the sleep time in line 248 from "sleep 0.1" to:
sleep 2.0

Ideas for Bugfix/Enhancement:
Either generally extend the sleep-time or adapt the sleep time dynamically

If you have further questions, please let me know.

**Comment by CTXz** [comment]
Thanks for the suggestion! 

With da5219ccaac102af89d74263ae54ce72c5676249, the script no longer relies on a delay but dynamically waits for the metadata file to be generated.

The metadata file should always be generated if the upload has succeeded. Should for some odd reason the metadata file not be generated, the script will simply hang at _"Accessing metadata for foo.pdf"_, forcing the user to cancel the script.
