### ISSUE TITLE
Request for new feature: Put the Wifi in the same state as it was before the transfer

### ISSUE THREAD

**Issue by schaefischaefi** [reHackable/scripts#6]
Hi,
Here is another little feature to enhance the repush.sh script

Currenty, after finishing the data transfer, the Wifi is always switched on again.
I am not using the wifi at all (because I love my privacy, and do not want to connect/transfer any data into the cloud). Therefore it would be better if the script determines the state of the wifi before the data transfer, then switches the wifi off, and then - at the end of the script - sets it back to the same state as it was in the beginning.

Thanks a lot for considering my request.

**Comment by Ameb** [comment]
I agree.
For reference on how to read the current state: https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-rfkill

**Comment by CTXz** [comment]
@Ameb Although I can recall that the `soft blocked` property was affected by the wifi settings in codex version `0.0.4.81`, it appears that in newer updates the wifi settings have no impact on rfkill properties anymore.

Are you aware of any other **reliable** methods to determine that current wifi state?

**Comment by CTXz** [comment]
With OS version `1.6.0.6`, this issue should no longer be present as of commit 12e1a8ffc949700b8a275175461908dec7ca52a3.

If wifi is re-enabled **prior** restarting the device, the device will maintain the wifi toggle in its ON state.
